### ISSUE TITLE
promotion of single to double 

### ISSUE THREAD

**Issue by bruceravel** [xraypy/feff85exafs#30]
One of the things I did in #28 was run the files in `src/POT` and `src/XSPH` through some static analyzers, including the venerable ftnchek.

In the files `src/POT/frnrm.f` and `src/POT/sumax.f`, ftnchek gives lots of warnings of this sort:

>     57          jbl = int(2.0+20.0*(blx+8.8))
>                                        ^
> Warning near line 57 col 33 file sumax.f: promotion may not give desired
>  precision: dble BLX + real const 8.8

One can explicitly promoting the constants, i.e.,

>     57          jbl = int(2.0d0+20.0d0*(blx+8.8d0))   

However, doing so results in a few unit test failures.  They're not big failures -- that is, I made some arbitrary decision about the level of precision at which I would compare numbers in the unit test suite.  These differences are not large compared to that decision.  Still, the results end up being a little bit different.  I suppose that it's because those two files have a lot of exponentiation, powers, and logarithms in them.

So, what the best thing to do?  Don't worry about promotion warnings?  Do the explicit promotion and recognize that the answers will be a bit different than the answers using as-delivered feff85exafs?  It seems likely that this level of difference will happen on other computers or with other compilers.

**Comment by newville** [comment]
I'd be +1 on making all constants and literals be explicitly double precision.

**Comment by bruceravel** [comment]
See 2bfee5683f575b50fba7aea5eb89a4698d02b31d
