### ISSUE TITLE
fundamental constants should be updated

### ISSUE THREAD

**Issue by newville** [xraypy/feff85exafs#34]
There are many file which have ever-so-slightly inaccurate values for fundamental constants:

* `bohr ` is given as 0.529177249 in code, should be 0.52917721067 
`src/POT/feffphases.h`
`src/OPCONSAT/oca_constants.f90`
`src/XSPH/getedg.f`
`src/HEADERS/const.h`

* `ryd` is given as 13.605698, should be 13.60569301 

`src/XSPH/getedg.f`
`src/HEADERS/const.h`

* `hbar` is given as 1.054572666e-34, should be  1.054571800e-34 
`src/DEBYE/sigcl.f` (and others here)
`src/OPCONSAT/oca_constants.f90`

**Comment by bruceravel** [comment]
All of those numbers are wrong in Feff6 as well.

**Comment by newville** [comment]
@bruceravel  they might just be out-of-date.  They're all sort of at the 7th decimal place.  Still, I think we should update them in Feff8L.

For updating them in Feff6L, I'm less sure.  Do we value "guaranteed reproducible" over "correct" for Feff6L?   No strong opinion on that, but I might lean toward "leave as is".

**Comment by bruceravel** [comment]
Definitely "leave as is".  I was just noticing that the wrong values for bohr et al have been in use for a looooong time.

**Comment by bruceravel** [comment]
The value for the [fine structure constant](http://physics.nist.gov/cgi-bin/cuu/Value?alphinv) is wrong also.

**Comment by newville** [comment]
this has been fixed now
